### PR TITLE
LPS-51522

### PR DESCRIPTION
**Pull request by bejondshao**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Beyond,
Please test following test case after you remove the code isDenied() :
I supposed the user you want to invite is user a and b
1. invite user a and b when you add a calendarbooking
2. login with user a and refuse the invitation
3. edit calendar booking and just click the save button (it should ask you if confirm the changing, click yes)

4 finally double check if the status of user a is changed (the correct status should be declined)

**Comment by bejondshao** [comment]
Hi Dale,

I test without my change, user a (declined), is still in declined. But user
b (accepted), is removed from accepted list.

I checked that. You mean after my change, user a is removed from
"declined", right?

So consider user b, he is removed by default. Can we consider this is a bug
or this is intended? Does this mean if an event is edited, it is changed to
a new event, so original user status is all cleared?

Bejond Shao

Jr. Engineer, Technical Support

Subscription Services

Liferay Dalian Software Co., Ltd.

**Comment by daledotshan** [comment]
Hey Bejond,
Could you please test your fix if break the fix https://issues.liferay.com/browse/LPS-42866?

**Comment by bejondshao** [comment]
Hi Dale,
I've tested that. I change code to "if (childCalendarBooking.isMasterBooking() &&
                childCalendarBooking.isDenied())", the issue in LPS-42866 appears.

After I remove "&& childCalendarBooking.isDenied()", the issue disappears. So my fix didn't broke it.

**Pull request closed without merging**
